config/routes.rb
Rails.application.routes.draw do
	root 'dom#index'
	get 'management' => 'dom#management'
	get 'contact' => 'dom#contact'
	get 'quizzs/answering' => 'quizzs#answering'
	get 'quizzs/answer' => 'quizzs#answer'
	get 'quizzs/check' 
	post 'quizzs/check' 
	get 'signup' => 'users#new'
	get 'edit' => 'users#edit'
	
	resources :users
 	resources :quizzs

	get '/login' => 'sessions#new'
	post 'login' => 'sessions#create'
	delete 'logout' => 'sessions#destroy'

end

app/models/quizz.rb
class Quizz < ActiveRecord::Base
	validates :question, :ans1, :ans2, :ans3, :ans4, presence: true
	validates :correctAns, numericality: { only_integer: true } 
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password
	validates :first_name, presence: true, length: { maximum: 50 }
	validates :last_name, presence: true, length: { maximum: 50 }
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, presence: true, length: { maximum: 255 },
			format: { with: VALID_EMAIL_REGEX },
			uniqueness: { case_sensitive: false }
	has_many :quizzs

	def admin?
	self.role == 'admin'
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  	protect_from_forgery with: :exception
	helper_method :current_user 

	def current_user 
  	@current_user ||= User.find(session[:user_id]) if session[:user_id] 
	end

	def require_user 
  	redirect_to '/login' unless current_user 
	end

	def require_admin 
  	redirect_to '/' unless current_user.admin? 
	end
end

app/controllers/dom_controller.rb
class DomController < ApplicationController

  	def index
  	end

  	def  contact
  	end
end

app/controllers/quizzs_controller.rb
class QuizzsController < ApplicationController
	
	before_action :require_user, :only=> [:home,:answering, :answer, :check, :index, :show]  
	before_action :set_quizz, only: [:show, :edit, :update, :destroy]
	before_action :require_admin, only: [:show, :index, :edit, :new, :create, :update, :delete, :destroy]

	# GET /quizzs
	# GET /quizzs.json
	def index
	@quizzs = Quizz.all
	end

	# GET /quizzs/1
	# GET /quizzs/1.json
	def show
	end

	# GET /quizzs/new
	def new
	@quizz = Quizz.new
	end

	# GET /quizzs/1/edit
	def edit
	end

	# POST /quizzs
	# POST /quizzs.json
	def create
	@quizz = Quizz.new(quizz_params)
	respond_to do |format|
		if @quizz.save
		format.html { redirect_to @quizz, notice: 'Quizz was successfully created.' }
		format.json { render :show, status: :created, location: @quizz }
		else
		format.html { render :new }
		format.json { render json: @quizz.errors, status: :unprocessable_entity }
      		end
    	end
  	end

	# PATCH/PUT /quizzs/1
	# PATCH/PUT /quizzs/1.json
  	def update
    	respond_to do |format|
      		if @quizz.update(quizz_params)
        	format.html { redirect_to @quizz, notice: 'Quizz was successfully updated.' }
        	format.json { render :show, status: :ok, location: @quizz }
      		else
        	format.html { render :edit }
        	format.json { render json: @quizz.errors, status: :unprocessable_entity }
      		end
    	end
  	end

  	# DELETE /quizzs/1
  	# DELETE /quizzs/1.json
  	def destroy
    	@quizz.destroy
    	respond_to do |format|
      	format.html { redirect_to quizzs_url, notice: 'Quizz was successfully destroyed.' }
      	format.json { head :no_content }
    	end
  	end

	# GET /quizzs/answering/1
	def answering
	@quizzs = Quizz.all
	end

	# GET /quizzs/answer/1
	def answer
	@quizz = Quizz.find(params[:id])
	end

	# PUT /quizzs/answering/1
	# PUT /quizzs/answering/1.xml
	def check
	@user = User.find(session[:user_id])
	@quizz = Quizz.find(params[:id])
	respond_to do |format|
		if params[:answer][0].to_i== @quizz.correctAns
		flash[:notice] = "Congratulation. You gave the correct answer to the question: " + 			@quizz.question
		UserMailer.test_result_positive(@user).deliver
		format.html { redirect_to({:controller => "quizzs", :action => "answering"} ) }
		format.xml { head :ok }
		else
		flash[:notice] = "I am sorry but that is not the right answer to the question: " + 			@quizz.question 
		UserMailer.test_result(@user).deliver
		format.html { redirect_to({:controller => "quizzs", :action => "answering"} ) }
		format.xml { head :ok }
		end
	end
	end

  	private
    	# Use callbacks to share common setup or constraints between actions.
    	def set_quizz
      	@quizz = Quizz.find(params[:id])
    	end

    	# Never trust parameters from the scary internet, only allow the white list through.
    	def quizz_params
      	params.require(:quizz).permit(:question, :ans1, :ans2, :ans3, :ans4, :correctAns)
    	end
	
	def user_params
	params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def new
	end

	def create
	@user = User.find_by_email(params[:session][:email])
  	if @user && @user.authenticate(params[:session][:password]) && @user.admin?
  	session[:user_id] = @user.id
  	redirect_to management_path
  	elsif @user && @user.authenticate(params[:session][:password])
    	session[:user_id] = @user.id
    	redirect_to root_path
  	else
    	redirect_to 'login'
  	end 
	end

	def destroy 
  	session[:user_id] = nil 
  	redirect_to '/' 
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def new
	@user = User.new
	end

	def create
	@user = User.new(user_params)
	if @user.save
	UserMailer.welcome(@user).deliver
	session[:user_id] = @user.id
	redirect_to '/'
	else
	redirect_to '/signup'
	end
	end

	def edit
	@user = User.find(session[:user_id])
	end
	
	def update 
	@user = User.find(session[:user_id])
	if @user.update_attributes(user_params)
	flash[:success] = "Profile updated"
	redirect_to root_path
	else
	flash[:notice] = "Your password and password confirmation are not identical."
	render 'edit'
	end
	end

	private
	def user_params
	params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dom_helper.rb
module DomHelper
end

app/helpers/quizzs_helper.rb
module QuizzsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/dom/contact.html.erb
<h1>Contact</h1>
<p>
  Contact author about the sample quizz app at the
  <a href="http://www.miki89.bitbucket.org">contact page</a>.
</p>

app/views/dom/index.html.erb
<br>
<br>
<div class="center jumbotron">
<h2><%= link_to "Visitor's Page - answering questions: ", {:controller => "quizzs", :action => "answering",:id=>"1" } %></h2>
<br>

app/views/dom/management.html.erb
<br>
<br>
<div class="center jumbotron">
<h2><%= link_to "Visitor's Page - answering questions: ", {:controller => "quizzs", :action => "answering",:id=>"1" } %></h2>
<br>

<h2><%= link_to 'Quizzes Management', quizzs_path %></h2>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer">
  
  <nav>
    <ul>
      <li><%= link_to "Contact", contact_path %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
	<nav>
          <ul class="nav navbar-nav navbar-right">
		<% if current_user %>
        	<li><%= current_user.email %></li>
        	<li><%= link_to "Profile", 'edit' %></li>
        	<li><%= link_to "Log out", logout_path, method: "delete" %></li>          
		<br>
		<br>
		<p align="right"><h1>Hello, <%= current_user.first_name %></h1></p>
          	<% else %>
                <li><%= link_to "Login", 'login' %></a></li>
            	<li><%= link_to "Signup", 'signup', class: "btn btn-lg btn-primary" %></a></li>
    	  	<% end %>
	  </ul>
	</nav>
      </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Quizzing</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<%= render 'layouts/header' %>
	<div class="container">
	<%= yield %>
	<%= render 'layouts/footer' %>
	</div>
</body>
</html>

app/views/quizzs/_form.html.erb
<%= form_for(@quizz) do |f| %>
  <% if @quizz.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@quizz.errors.count, "error") %> prohibited this quizz from being saved:</h2>

      <ul>
      <% @quizz.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :question %><br>
    <%= f.text_area :question %>
  </div>
  <div class="field">
    <%= f.label :ans1 %><br> 
    <%= f.text_area :ans1 %>
   
  </div>
  <div class="field">
    <%= f.label :ans2 %><br>
    <%= f.text_area :ans2 %>
    
  </div>
  <div class="field">
    <%= f.label :ans3 %><br>
    <%= f.text_area :ans3 %>
    
  </div>
  <div class="field">
    <%= f.label :ans4 %><br>
    <%= f.text_area :ans4 %>
    
  </div>
  <div class="field">
    <%= f.label :correctAns %><br>
    <%= f.number_field :correctAns %>
    
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/quizzs/answer.html.erb
<br>
<br>
<h2><p>
<b>Question:</b>
<%=h @quizz.question %>
</p>
<p>
<b>1</b>
<%=h @quizz.ans1 %>
</p>
<p>
<b>2</b>
<%=h @quizz.ans2 %>
</p>
<p>
<b>3</b>
<%=h @quizz.ans3 %>
</p>
<p>
<b>4</b>
<%=h @quizz.ans4 %>
</h2></p>
<%= form_tag(:action => "check",:id => @quizz.id) do %>
<p>
<b>The correct answer is number: </b>
<%= text_field :answer, params[:answer] %>
</p>
<p><%= submit_tag("check") %></P>
<% end %>

<%= link_to 'Back', {:controller => "quizzs", :action => "answering",:id=>"1" } %>

app/views/quizzs/answering.html.erb
<p id="notice"><%= notice %></p>
<br>
<br>
<h2>Which question do you want to answer?</h2>
<table>
<tr>

<th>Question</th>
</tr>
	<% @quizzs.each do |quizz| %>
	<tr>
	<td><%= quizz.question %></td>
	<td><%= link_to ' Answer this', :controller => "quizzs", :action => "answer",:id=>quizz.id %>
	</td>
	</tr>
	<% end %>
</table>
</br>
<%= link_to 'Back', root_path %>

app/views/quizzs/edit.html.erb
<h1>Editing Quizz</h1>

<%= render 'form' %>

<%= link_to 'Show', @quizz %> |
<%= link_to 'Back', quizzs_path %>

app/views/quizzs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Quizzs</h1>

<table>
  <thead>
    <tr>
      <th>Question</th>
      <th>Ans1</th>
      <th>Ans2</th>
      <th>Ans3</th>
      <th>Ans4</th>
      <th>Correctans</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @quizzs.each do |quizz| %>
      <tr>
        <td><%= quizz.question %></td>
        <td><%= quizz.ans1 %></td>
        <td><%= quizz.ans2 %></td>
        <td><%= quizz.ans3 %></td>
        <td><%= quizz.ans4 %></td>
        <td><%= quizz.correctAns %></td>
        <td><% if current_user && current_user.admin? %> <%= link_to 'Show', quizz %></td>
        <td> <%= link_to 'Edit', edit_quizz_path(quizz) %></td>
        <td> <%= link_to 'Destroy', quizz, method: :delete, data: { confirm: 'Are you sure?' } %></td><% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Quizz', new_quizz_path %>
<br>
<%= link_to 'Back', management_path %>

app/views/quizzs/new.html.erb
<h1>New Quizz</h1>

<%= render 'form' %>

<%= link_to 'Back', quizzs_path %>

app/views/quizzs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Question:</strong>
  <%= @quizz.question %>
</p>

<p>
  <strong>Ans1:</strong>
  <%= @quizz.ans1 %>
</p>

<p>
  <strong>Ans2:</strong>
  <%= @quizz.ans2 %>
</p>

<p>
  <strong>Ans3:</strong>
  <%= @quizz.ans3 %>
</p>

<p>
  <strong>Ans4:</strong>
  <%= @quizz.ans4 %>
</p>

<p>
  <strong>Correctans:</strong>
  <%= @quizz.correctAns %>
</p>

<%= link_to 'Edit', edit_quizz_path(@quizz) %> |
<%= link_to 'Back', quizzs_path %>

app/views/users/edit.html.erb
<h1>Update your profile</h1>
<p id="notice"><%= notice %></p>
<%= form_for(@user) do |f| %>

<%= f.text_field :first_name, :placeholder => "First name" %>
<%= f.text_field :last_name, :placeholder => "Last name" %>
<%= f.email_field :email, :placeholder => "Email" %>
<%= f.password_field :password, :placeholder => "Password" %>
<%= f.password_field :password_confirmation, :placeholder => "Password confirmation" %>
<%= f.submit "Update profile", class: "btn-submit" %>
<% end %>
<br>
<%= link_to 'Back', root_path %>

app/views/users/new.html.erb
<h1>Sign up</h1>

 <%= form_for(@user) do |f| %>
      <%= f.text_field :first_name, :placeholder => "First name" %>
      <%= f.text_field :last_name, :placeholder => "Last name" %>
      <%= f.email_field :email, :placeholder => "Email" %>
      <%= f.password_field :password, :placeholder => "Password" %>
      <%= f.submit "Create an account", class: "btn-submit" %>
    <% end %>